make sure a new tab is selected tab when removing tab group
neevaco/neeva-ios pull request #3107
Opened 2022-03-15 00:20 UTC by chassu

There's a bug when removing tab group - when the selectedTab is not the last tab in the tab group, a new tab won't be selected, and clicking done button will show the deleted tab's webview.

## Checklists

### How was this tested?
- [x] I tested this manually

### Screenshots and screen recordings
Before:

https://user-images.githubusercontent.com/87332917/158281905-e8687c3d-5e7c-44d1-bd1b-4ee8b55400e7.mp4

After:

https://user-images.githubusercontent.com/87332917/158281917-366fc884-cef0-4982-90f0-c807dd7db460.mp4

2022-03-15 00:29 UTC, evancrow approved these changes
LGTM

2022-03-15 06:33 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager+CloseTabs.swift
> +        } else if tab == selectedTab || tab.rootUUID == selectedTab?.rootUUID {
I'm not sure I understand this check. It seems like one approach would be to just check if `selectedTab` is still part of `tabs`. If it is, then great. No work is needed. If it is not, then we need to update `selectedTab`. Simple and probably the most robust solution here.

```
} else if !tabs.contains(selectedTab) {
    // Update selectedTab
    ...
}
```

2022-03-15 06:33 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager+CloseTabs.swift
>              DispatchQueue.main.async {
Hmm... in this scenario, perhaps we should be setting selectedTab to nil? And shouldn't we also generate notifications for the selected tab changing?

2022-03-15 22:55 UTC, chassu commented on Client/Frontend/Browser/Tabs/TabManager/TabManager+CloseTabs.swift
>              DispatchQueue.main.async {
I'm actually not sure what could break when we don't set it to nil in such scenario. Made some changes based on your comments though. Let me know if it looks right.

2022-03-21 19:44 UTC, darinwf reviewed
This change deserves some test coverage.

2022-03-21 19:44 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager+CloseTabs.swift
> +                self.selectedTabPublisher.send(nil)
I think you need to honor `notify` here.

2022-03-21 19:44 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager+CloseTabs.swift
> +        } else if let selectedTab = selectedTab, !viableTabs.contains(selectedTab) {
Hmm... perhaps we should update the below to determine the next selected tab relative to the previously selected tab, instead of doing so relative to `tab`?

2022-03-24 21:45 UTC, chassu commented on Client/Frontend/Browser/Tabs/TabManager/TabManager+CloseTabs.swift
> +                self.selectedTabPublisher.send(nil)
where are we passing the notify to?

2022-03-25 21:58 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager+CloseTabs.swift
> +                self.selectedTabPublisher.send(nil)
the `notify` parameter passed to this function is used to suppress notifications like the one you are sending here.

2022-03-25 21:58 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager+CloseTabs.swift
>              DispatchQueue.main.async {
I think you should just call `selectTab(nil, notify: notify)` here instead

2022-03-28 05:01 UTC, darinwf requested changes
See latest comments for what is needed.

2022-03-28 06:18 UTC, darinwf approved these changes

2022-03-28 18:04 UTC, merged