Only Updated Update Selected Tab, If No Tab Selected (RestoreTabs)
neevaco/neeva-ios pull request #3108
Opened 2022-03-15 02:57 UTC by evancrow

Pointed out by @chassu, but when restoring tabs it will override the selected tab which can be pretty annoying. Now will only pick the selected tab when restoring, if no tab is currently selected.

## Checklists
### How was this tested?
- [x] I tested this manually
- [ ] I added automated tests
- [ ] Existing automated tests are enough to cover my changes

2022-03-15 03:04 UTC, chassu approved these changes

2022-03-16 00:26 UTC, evancrow commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +            if let selectedTab = selectedTab, !tabs.contains(selectedTab) {
Found a related issue where the `selectedTab` was not being reset if it was closed. Didn't cause any problems, but the state was still wrong.

2022-03-16 06:12 UTC, darinwf requested changes

2022-03-16 06:12 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +            if let selectedTab = selectedTab, !tabs.contains(selectedTab) {
Shouldn't we just update the logic in `updateSelectedTabAfterRemovalOf` to handle whatever case is missing? It seems a bit confusing to have two places where we try to update the select tab after removing a tab. It also should be the case that we call `selectTab(nil)` when we want to set `selectedTab` to nil. That function takes care to store tabs state after changing which tab is selected. (Note, I think `selectTab(nil)` case might have some issues with updating incognito mode that would need to be addressed.)

2022-03-17 03:30 UTC, darinwf requested changes

2022-03-17 03:30 UTC, darinwf commented on Client/Frontend/Browser/Card/CardModels.swift
> +            guard let tab = tabCard.manager.get(for: tabCard.id) else {
We have been trying to not add this change but to keep the force unwrapping to help us find cases where TabCardModel and TabManager are not in sync. Did you hit one of those cases as part of developing this PR?

2022-03-17 03:30 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager+CloseTabs.swift
>                  bvc.showTabTray()
I think we should eventually move this logic to BVC and have it do this when it observes TabManager.tabs become empty, but that is for another change.

2022-03-17 03:30 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager+CloseTabs.swift
> +            self.selectTab(nil)
I think you might need to pass the `notify` parameter to `selectTab` here to avoid the crash that you were seeing in `buildRows`

2022-03-17 03:32 UTC, evancrow commented on Client/Frontend/Browser/Card/CardModels.swift
> +            guard let tab = tabCard.manager.get(for: tabCard.id) else {
This is why the tests were failing. I you want to try it out, revert this change and run the `EmptyTabTrayTests`.

2022-03-17 03:33 UTC, evancrow commented on Client/Frontend/Browser/Tabs/TabManager/TabManager+CloseTabs.swift
> +            self.selectTab(nil)
Ah okay!

2022-03-17 03:48 UTC, darinwf commented
@chassu - FYI, Maybe we should have made the `notify` parameter to `selectTab` a required parameter.

2022-03-19 00:12 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager+CloseTabs.swift
> +            self.selectTab(nil, notify: false)
I think you want to just forward the `notify` parameter here. That way the caller can control whether or not to allow notifications. Just like the other calls to `selectTab` below.

2022-03-29 02:54 UTC, evancrow commented
I'm going to close this PR, not really going anywhere, not really solving anything

2022-03-29 02:54 UTC, closed without merging