Add NetworkManager to WalletCore
neevaco/neeva-ios pull request #3208
Opened 2022-03-24 17:01 UTC by buracules

- Created a NetworkManager for WalletCore
- Created 2 APIs (OpenSeaAPI and CurrencyStoreAPI)

## Checklists

### How was this tested?
- [x] I tested this manually
- [ ] I added automated tests
- [ ] Existing automated tests are enough to cover my changes

### Manual test cases
I only tested with `.get` methods. if we wanna expand this manager it's better we use something like `Alamofire` otherwise we have to develop every encoding from scratch.

2022-03-29 06:06 UTC, yozuysal reviewed
looks great overall! One q about initialization then we are good to go

2022-03-29 06:06 UTC, yozuysal commented on WalletCore/Network/Web3NetworkProvider.swift
> +    public static let `default`: Web3NetworkProvider = {
should we use lazy?

2022-03-29 15:59 UTC, yozuysal approved these changes

2022-04-18 19:04 UTC, buracules commented on WalletCore/Network/Web3NetworkProvider.swift
> +    public static let `default`: Web3NetworkProvider = {
It says `'lazy' cannot be used on an already-lazy global` 😀

2022-04-18 19:05 UTC, yozuysal commented on WalletCore/AssetStore.swift
> +                    onCompletion?()
we should only run onCompletion when we didn't get any next cursor in the result. Otherwise this will run it multiple times for every paginated fetch

2022-04-18 19:21 UTC, yozuysal approved these changes

2022-04-18 19:36 UTC, yozuysal commented on WalletCore/Network/APIs/OpenSeaAPI.swift
> +                    "X-API-KEY": apiKey,
I dont think we need this for collections btw

2022-04-18 19:38 UTC, yozuysal requested changes

2022-04-18 19:38 UTC, yozuysal commented on WalletCore/AssetStore.swift
> -            assets = []
we might want to make sure we reset this below or in some other way

2022-04-18 20:46 UTC, yozuysal approved these changes
we need to add limit=50 and we are good to go.

2022-04-18 21:42 UTC, merged