Charles time based switcher no selected tab state
neevaco/neeva-ios pull request #3397
Opened 2022-04-19 02:38 UTC by chassu

Add a state where none of the tab is selected. This happens when the last tab in the today section is closed.

## Checklists

### How was this tested?
- [x] I tested this manually

### Manual test cases

1. close last tab in today section using close button
2. close last tab in today section using card detail's long press menu
3. close last tab in today section using switcher tool bar's long press menu
4. close a tab in last week's section when no tab is selected

### Screenshots and screen recordings

https://user-images.githubusercontent.com/87332917/163908555-f109987d-4840-41ea-8d9f-762e8456a1f6.mp4

2022-04-19 02:57 UTC, evancrow commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +            !(tabsFiltered.count == 1 && tabsFiltered[0].tabUUID == tab.tabUUID
I'm concerned that if `tabsFiltered` is empty then this will crash with an `index not in range` error. Can you try using `.first` and unwrapping that?

(this also applies to other places as well)

2022-04-19 03:04 UTC, chassu commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +            !(tabsFiltered.count == 1 && tabsFiltered[0].tabUUID == tab.tabUUID
but if the first condition evaluates to false, the rest of the conditions won't be evaluated. Doesn't that avoid the index problem?

2022-04-19 03:10 UTC, evancrow commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +            !(tabsFiltered.count == 1 && tabsFiltered[0].tabUUID == tab.tabUUID
If you unwrap` .first` it will be a cleaner, "swiftier" solution. Relying on a specific count can sometimes lead to bugs later on.

2022-04-19 20:17 UTC, darinwf requested changes

2022-04-19 20:17 UTC, darinwf commented on Client/Frontend/Browser/BrowserViewController/BrowserViewController+TabToolbarDelegate.swift
> +    func isLastSelectedTabTodaySection(tab: Tab) -> Bool {
nit: suggest renaming to `isLastSelectedTabInTodaySection` <- note the "In" addition ... actually, we shouldn't encode "Today" here since the first section may not contain just tabs from today, right? This the recent tabs section. Should choose a name to reflect that reality.

2022-04-19 20:17 UTC, darinwf commented on Client/Frontend/Browser/BrowserViewController/BrowserViewController+TabToolbarDelegate.swift
> +    func isLastSelectedTabTodaySection(tab: Tab) -> Bool {
Why isn't this method just the same as `shouldSelectNewTabAfterRemovalOf`? Why is the logic different...

2022-04-19 20:17 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +        case .today:
I'm confused about the time segmentation here. You have tabs from today and tabs from last week? What about tabs from the days in between? Oh... lastWeek seems to be inclusive of the tabs used yesterday? I would think tabs from last week should not include tabs from yesterday.

2022-04-19 20:17 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> -    public static func makeWebViewConfig(isIncognito: Bool) -> WKWebViewConfiguration {
What was the purpose of moving this function?

2022-04-19 20:17 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager+CloseTabs.swift
> +        let bvc = SceneDelegate.getBVC(with: scene)
Can we please avoid adding dependencies on BVC from `TabManager`? If we want to have the tab tray show when there is no selected tab, then BVC should just do so via a sink attached to selectedTabPublisher, right?

2022-04-19 20:17 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +    func filterTabByTime(tab: Tab, byTime: TimeFilter) -> Bool {
Maybe this should be a method on `Tab` instead? It doesn't seem to use any state from `TabManager`. The name could also be improved, something like: `tab.wasLastExecuted(.today)` which reads nicely and aligns to the `lastExecutedTime` property of `Tab`.

The definition of `TimeFilter` should also move to `Tab.swift` accordingly.

2022-04-19 20:17 UTC, darinwf commented on Client/Frontend/Browser/BrowserViewController/BrowserViewController+TabToolbarDelegate.swift
> +                || self.tabCardModel.allDetailsWithExclusionList.contains { $0.id == tabCard.id })
I think you should avoid using IDs for equality checks. See https://github.com/neevaco/neeva-ios/pull/3403 for reference. You should just compare the `TabCardDetails` to another `TabCardDetails` directly. `TabCardDetails` conforms to `Equatable` afterall.

2022-04-19 20:17 UTC, darinwf commented on Client/Frontend/Browser/BrowserViewController/BrowserViewController+TabToolbarDelegate.swift
> +                && tab.isIncognito
Why are you checking incognito here?

2022-04-20 22:41 UTC, chassu commented on Client/Frontend/Browser/BrowserViewController/BrowserViewController+TabToolbarDelegate.swift
> +    func isLastSelectedTabTodaySection(tab: Tab) -> Bool {
I forgot to change this part. I was going to use `shouldSelectNewTabAfterRemovalOf` instead and remove this function.

2022-04-20 22:44 UTC, chassu commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +        case .today:
Hm, I thought we had this discussion before. I thought the definition for the sections are:
today: {set of tabs whose last used time is < 24 hours}
last week: {set of tabs whose last used time is < 7 days - {today}}

If tabs from yesterday don't belong to last week, then where do they go? It feels weird to be to include them in "today"'s section.

2022-04-20 22:48 UTC, chassu commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> -    public static func makeWebViewConfig(isIncognito: Bool) -> WKWebViewConfiguration {
I didn't mean to modify this part but it happened when I cherry-picked the very first commit into this branch. I end up place it in where it lives on the main branch. I think this should be fine once #3379 is merged.

2022-04-20 22:52 UTC, chassu commented on Client/Frontend/Browser/BrowserViewController/BrowserViewController+TabToolbarDelegate.swift
> +                && tab.isIncognito
This function is removed. But `shouldSelectNewTabAfterRemovalOf` uses incognito as a filter so I'll explain - it's because we want to make sure that no tab is selected when the last tab in today's section is closed. The tabs array contains all tabs including both incognito and normal tabs. So I need the filter to make sure we don't include incognito tabs.

2022-04-21 16:21 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +        case .today:
I thought we made a decision to call this section "Recent" instead of "Today". Please confirm with Ria, but see also: https://www.figma.com/file/t1jW7cahkClVHAIlnHJuv8/Tab-Manager-(Spaces-%26-Tab-Groups)?node-id=3264%3A12992

2022-04-21 18:41 UTC, chassu commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +        case .today:
I looked up the meeting notes before and can confirm we decided to start with recent. Do you think it's better to include yesterday's tabs to recent section?

2022-04-25 22:08 UTC, chassu commented
can confirm the issue above has been resolved (also made a minor change to check if any card is selected instead of isEmpty)

2022-05-03 05:54 UTC, darinwf commented on Client/Frontend/Browser/BrowserViewController/BrowserViewController+TabToolbarDelegate.swift
> +                            updateSelectedTab: self.tabManager.shouldSelectNewTabAfterRemovalOf(
nit: It seems a bit awkward to have `tabManager.removeTab`'s `updateSelectedTab` parameter determined by another method of `TabManager`. Why doesn't `TabManager` just call its own method directly? I guess the answer is that you don't want to run this logic in all cases. Perhaps that difference should be expressed by inventing a new variant of `removeTab` that is named differently, appropriately setting it apart from normal `removeTab`?

2022-05-03 05:54 UTC, darinwf commented on Client/Frontend/Browser/Tabs/Tab.swift
> +    case today = "Today"
It's a separate matter from this PR, but we should revisit the definition of these categories. Our History UI has Today, Yesterday and Last Week. Perhaps we should standardize on those as well.

I don't think it makes sense to define Today as within the last 24 hours as that includes yesterday, but we can discuss separately.

2022-05-03 05:54 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager+CloseTabs.swift
> +            self.selectTab(nil, notify: true)
It doesn't make sense that in the `!updateSelectedTab` case we are calling `selectTab`. That's updating the selected tab. Perhaps the parameter is now misnamed?

2022-05-03 05:54 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +    private(set) var noSelectedTabStatePublisher = PassthroughSubject<Void, Never>()
This is stale.

2022-05-03 05:54 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +        let tabsFiltered = tabs.filter {
nit: I think you can optimize this function a bit to just count the number of tabs executed today. There's no need to generate an array of all tabs from today to implement this function.

That said, another approach here could be to revise updateSelectedTabAfterRemovalOf to handle this logic. After the tab has been removed, you can just scan the array to see if there is any remaining tab in the today section. Wouldn't that be simpler?

2022-05-04 01:15 UTC, chassu commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +        let tabsFiltered = tabs.filter {
I removed `shouldSelectNewTabAfterRemovalOf` and handle the logic inside `updateSelectedTabAfterRemovalOf`. Let me know what you think.

2022-05-04 18:49 UTC, darinwf approved these changes
LGTM

2022-05-04 18:49 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager+CloseTabs.swift
> +                ? !viableTabs.contains(where: { $0.wasLastExecuted(.today) }) : false)
So much simpler, right?!

2022-05-05 00:56 UTC, merged