scroll to selected tab from history view
neevaco/neeva-ios pull request #3406
Opened 2022-04-19 22:01 UTC by chassu

### How was this tested?
- [x] I tested this manually

### Screenshots and screen recordings
before:

https://user-images.githubusercontent.com/87332917/164108913-575826df-33e4-4e38-abdb-54605aa4e1ba.mp4

after:

https://user-images.githubusercontent.com/87332917/164108937-c8f5773a-ad86-4298-ac98-2270def9572d.mp4

2022-04-20 05:39 UTC, darinwf commented
Hmm... tapping on an item in History should use createOrSwitchToTab and **bring the selected tab to the foreground**. It is perhaps a regression from the new SwiftUI-based History UI that that isn't happening now.

2022-04-20 05:52 UTC, darinwf commented
Something like this:
```
diff --git a/Client/Frontend/Browser/BrowserViewController.swift b/Client/Frontend/Browser/BrowserViewController.swift
index d9fd2f0e9..6a4da31ed 100644
--- a/Client/Frontend/Browser/BrowserViewController.swift
+++ b/Client/Frontend/Browser/BrowserViewController.swift
@@ -1494,6 +1494,10 @@ extension BrowserViewController {
         }
 
         updateInZeroQuery(selected?.url as URL?)
+
+        if selected != nil {
+            hideCardGrid(withAnimation: false)
+        }
     }
 
     func getSceneDelegate() -> SceneDelegate? {
```

2022-04-25 05:11 UTC, darinwf requested changes
See comment above on suggested change.

2022-04-26 01:20 UTC, chassu commented
https://user-images.githubusercontent.com/87332917/165200003-8227051f-2c76-413c-982f-8e487d66a3b1.mp4

2022-04-26 05:12 UTC, chassu commented
looks the that fix alone is causing the normal card transition animation to fail. will investigate it.

2022-05-02 21:23 UTC, darinwf commented on Client/Frontend/Site/SiteRowView.swift
> +                browserModel.hideGridWithNoAnimation()
Can this be moved within the `openURL` handler? I feel like it is a lot for `SiteRowView` to have to know about hiding the grid.

2022-05-02 21:23 UTC, darinwf commented on Client/Frontend/Site/SiteRowView.swift
> +                browserModel.hideGridWithNoAnimation()
Yeah, `HistoryPanelViewController` seems like a better spot for this. WDYT?

2022-05-02 23:17 UTC, chassu commented on Client/Frontend/Site/SiteRowView.swift
> +                browserModel.hideGridWithNoAnimation()
makes sense to me!

2022-05-03 17:46 UTC, darinwf approved these changes

2022-05-03 17:47 UTC, darinwf commented
When you commit be sure to update the commit log entry accordingly since this PR evolved a lot since the start :)

2022-05-03 18:53 UTC, merged