Charles time based switcher history view
neevaco/neeva-ios pull request #3593
Opened 2022-05-13 05:24 UTC by chassu

This is still WIP and there are some issues I'm aware of, but I think some parts of it can be already reviewed to save some time.

Some issues that I'm aware of:

- Card transition animation is missing the first time when a tab is brought back from archives. (select a tab in archives -> webview shows up -> click switcher button)
- There should be a more granular way for the switcher to update tab groups when a tab is brought back from archives. (I temporarily change `updateRows` to `onDataUpdated` as a proof of concept). This is different from `buildRows` which is called when a tab is selected. By introducing archived tabs, there's a chance a tab group can be formed simply by selecting tabs from archives.
- Clear All Archived Tabs doesn't do anything yet
- ArchivedTabsPanelView refreshes on click (not ideal IMO)

An issue unrelated to this PR:

- I assume something about `FaviconView` is making the favicon changing values back and forth. Can be seen in the ArchivedTabsPanelView and it has existed in our tab switcher too, especially when a webview is loading.

## Checklists

### How was this tested?
- [x] I tested this manually

https://user-images.githubusercontent.com/87332917/168216076-c3da13ab-ef2f-48d5-a39b-60722d9596dd.mp4

2022-05-13 16:52 UTC, evancrow reviewed
Coming along well! Think a lot of next steps are just code cleanup and refactoring.

2022-05-13 16:52 UTC, evancrow commented on Client/Frontend/Browser/Card/ArchivedTabsPanelModel.swift
> +enum ArchivedTabTimeSection: String, CaseIterable {
Should be able to reuse the time enum from `HistoryModel` here instead of creating a new one.

2022-05-13 16:52 UTC, evancrow commented on Client/Frontend/Browser/Card/ArchivedTabsPanelModel.swift
> +    var representativeTabsInAMonth: [Tab] = []
Shouldn't need these if you have `groupedSites` right?

2022-05-13 16:52 UTC, evancrow commented on Client/Frontend/Browser/Card/ArchivedTabsPanelView.swift
> +                        Group {
What is the point of this empty `Group`? Is it still WIP?

2022-05-13 16:52 UTC, evancrow commented on Client/Frontend/Browser/Card/ArchivedTabsView.swift
> +    var bvc: BrowserViewController {
I don't think you should plumb down `tabModel` to get the `BVC`. Would be better to create a callback in `ArchivedTabsView` that is set in a place that doesn't need the plumbing.

2022-05-13 16:52 UTC, evancrow commented on Client/Frontend/Browser/Card/ArchivedTabsPanelViewController.swift
> +            .environmentObject(bvc.browserModel)
I don't think these need to be passed down. This was for the `OverlayView` in settings which isn't being used here.

2022-05-13 16:52 UTC, evancrow commented on Client/Frontend/Browser/Card/TabListView.swift
> +struct ButtonView: View {
Should give this a more descriptive name.

2022-05-13 19:07 UTC, chassu commented on Client/Frontend/Browser/Card/ArchivedTabsPanelModel.swift
> +enum ArchivedTabTimeSection: String, CaseIterable {
I changed it to reuse the enum from history, but some enum cases won't be used. Can you take a look and let me know if it looks fine? I originally separated them because I thought it would be awkward to have unused enum cases.

2022-05-14 00:14 UTC, evancrow commented on Client/Frontend/Browser/Card/ArchivedTabsPanelModel.swift
> +enum ArchivedTabTimeSection: String, CaseIterable {
Think you're right that it doesn't make sense to have an unused enum. Guess the way you had it before is fine.

2022-05-17 22:19 UTC, chassu commented on Client/Frontend/Browser/Card/ArchivedTabsPanelModel.swift
> +    }
I was hoping `ArchivedTabsPanelView` will pick up the change right when a user selects a new setting inside `ArchivedTabSettings.` But this doesn't seem to do anything. @evancrow  Thoughts?

The purpose of this is to ensure after the user selects a new settings, hit the back button and they will see an updated `ArchivedTabsPanelView` because the filtering logic has changed.

2022-05-18 00:57 UTC, chassu commented on Client/Frontend/Browser/Card/ArchivedTabsPanelModel.swift
> +    }
After an "optimization" I thought I made - avoid calling `onDataUpdated` when active tabs are selected, I realized that the tab switcher doesn't respond to `archivedTabsDuration` settings changes, and the user won't see the correct tabs unless they add/remove a tab. I have an idea for this now and am going to try it out. But I want to point out this issue.

2022-05-18 18:20 UTC, chassu commented on Client/Frontend/Browser/Card/ArchivedTabsPanelModel.swift
> +    }
Resolved by changing '.' to '_' for the user default key... 🙄

2022-05-18 21:51 UTC, chassu commented
won't make anymore functionality changes on this PR, will work on cleanups for now.

2022-05-20 22:29 UTC, chassu commented on Client/Frontend/Browser/Card/ArchivedTabsListView.swift
> +                FaviconView(forSiteUrl: tab.url ?? "")
There could be a migration issue here, I just experienced a crash caused by `tab.url` used to not being stored, and the fallback "" will lead to crash when the `FaviconView` takes in an empty string as a parameter.

2022-05-20 22:29 UTC, chassu commented on Client/Frontend/Browser/Card/ArchivedTabsListView.swift
> +                FaviconView(forSiteUrl: tab.url ?? "")
There could be a migration issue here, I just experienced a crash caused by `tab.url` used to not being stored, and the fallback "" will lead to crash when the `FaviconView` takes in an empty string as a parameter.

2022-05-23 21:41 UTC, evancrow commented on Client/Frontend/Browser/Card/ArchivedTabsListView.swift
> +                FaviconView(forSiteUrl: tab.url ?? "")
Unwrap the `URL` before the `FaviconView` instead of passing an empty `String`?

2022-05-23 21:41 UTC, evancrow commented on Client/Frontend/Browser/Card/ArchivedTabsListView.swift
> +                    if processed[tab.rootUUID] == false {
Can you try to reduce the number of nested `if`s here?

2022-05-23 21:41 UTC, evancrow commented on Client/Frontend/Browser/Card/ArchivedTabsPanelView.swift
> +                        Group {
Is this group supposed to be empty?

2022-05-23 21:41 UTC, evancrow commented on Client/Frontend/Browser/Card/ArchivedTabsPanelView.swift
> +            LazyVStack(spacing: 0, pinnedViews: .sectionHeaders) {
You shouldn't need to embed `LazyVStack`s inside a `LazyVStack`. I think you can keep the outermost one, and then make `ArchivedTabsListView` a `VStack`. Also maybe `ArchivedTabsListView` should be renamed to `ArchivedTabsListSectionView`?

2022-05-24 01:40 UTC, chassu commented on Client/Frontend/Browser/Card/ArchivedTabsPanelView.swift
> +            LazyVStack(spacing: 0, pinnedViews: .sectionHeaders) {
Did the inner `LazyVStack` because I thought about an archived tab group that has 100 tabs and wonder if we want to do lazy loading for those.

2022-05-24 01:41 UTC, chassu commented on Client/Frontend/Browser/Card/ArchivedTabsPanelView.swift
> +            LazyVStack(spacing: 0, pinnedViews: .sectionHeaders) {
^changed to what you recommended

2022-05-24 19:12 UTC, evancrow commented on Client/Frontend/Browser/Card/ArchivedTabsListView.swift
> +                    if processed[tab.rootUUID] == false {
Yeah, `AnyView` isn't great. If we really wanted to refactor this, could make the code inside the `if` its own `View`, but I think this is fine for now.

2022-05-24 22:38 UTC, chassu commented on Client/Frontend/Browser/Card/CardModels.swift
> +        } else if needsUpdateRows || force {
maybe change `force` to `forceUpdateRows` here?

2022-05-25 07:27 UTC, darinwf reviewed
Looking pretty good. Just some flags.

2022-05-25 07:27 UTC, darinwf commented on Client/Frontend/Browser/Card/ArchivedTabsPanelViewController.swift
> +    init(bvc: BrowserViewController) {
How about just passing `BrowserModel` here since it also has a reference to the `TabManager`? That way we avoid one more dependency on BVC.

2022-05-25 07:27 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +    var activeTabGroups: [String: TabGroup] {
I wonder if this will be an expensive to compute property. I wonder if we should compute and store the results to help speed things up.

2022-05-25 07:27 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +        return getAll()
Ditto

2022-05-25 07:27 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +            updateGroupPublisher.send()
this should be only within the `notify` block below. we want to avoid all notifications if `notify` is false.

2022-05-25 07:27 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +        let tabsToKeep = self.tabs.filter { !archivedTabs.contains($0) }
should this just be using `removeTabs` passing the set of archived tabs? Why re-invent another variant of the `removeTabs` function?

2022-05-25 22:13 UTC, chassu commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +    var activeTabGroups: [String: TabGroup] {
This computed property is only called once during `onDataUpdated` and the information is technically stored inside allTabGroupDetails. I feel like this is okay..

2022-05-25 22:17 UTC, chassu commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +        return getAll()
I made `ArchivedTabsPanelModel` store `archivedTabGroups` during init, which is the only time this computed property ever get evaluated. Are we good with this?

2022-05-25 22:19 UTC, chassu commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +        let tabsToKeep = self.tabs.filter { !archivedTabs.contains($0) }
`removeTabs` sends notifications such as `updateTabGroupsAndSendNotifications(notify: true)` and `sendSelectTabNotifications(previous: previous)` which I think we want to avoid when clearing archived tabs. I've switched to `removeTabs` but had to add extra logic to skip sending signals. Not sure if it's better.

2022-05-25 22:29 UTC, chassu commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +        return getAll()
Well, if the user spams the ArchivedTabsPanelModel, we'll keep computing the property over and over again, which is probably not ideal, but one caveat: some tabs could get archived while the user spams it, so I think the question to ask here is "should we recalculate the archivedTabs/archivedTabsGroups every time a user launch the ArchivedTabsPanelView"? It might be good to get the most updated data, but I have a feeling that the chance of some tabs getting archived when the user is interacting with the ArchivedTabsPanelView is very very low.

2022-05-26 01:12 UTC, evancrow commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +    var activeTabGroups: [String: TabGroup] {
Could make this a regular var and then update it in `updateTabGroups` or whenever tabs are archived/unarchived.

2022-05-29 08:07 UTC, chassu commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +            .reduce(into: [String: [Tab]]()) { dict, tab in
I'm not sure how to refactor this function (reduce -> filter -> reduce). Any tips?

2022-05-29 08:16 UTC, chassu commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +            }
As requested, I changed `activeTabGroups` and `archivedTabGroups` into stored property. They are updated every time `updateTabGroupsAndSendNotifications` happens (could happen when 1. add tabs 2. close tabs 3. bring tabs back from archives). Compared with defining them as computed variables, this saves some computing from launching the `ArchivedTabsPanelView`, but adds compute to  `updateTabGroupsAndSendNotifications` since now it's computing activeTabGroups, archivedTabGroups, and `cleanUpTabGroupNames()` also becomes a bit more expensive to compute.

2022-05-29 08:17 UTC, chassu commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +            }
ArchivedTabGroups or ActiveTabGroups can't be used here, still need the old definition for all tab groups.

2022-06-01 06:02 UTC, chassu commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
>              }
@darinwf I know we talked about the change to run two loops with `activeTabGroups` and `archiveTabGroups`, but this leads to inconsistency in tab group titles as the group title is first child's title by default. If child tabs span across active and archived sections, it could show different titles even if the tabs belong to the same group.

2022-06-01 06:04 UTC, chassu commented on Client/Frontend/Browser/Tabs/TabGroup.swift
> +            ?? Date.nowMilliseconds()
https://github.com/neevaco/neeva-ios/issues/3739 is causing same tab group to show up in different sections, so I thought about creating lastExecutedTime for TabGroup...

2022-06-01 06:07 UTC, darinwf commented on Client/Frontend/Browser/BrowserModel.swift
> -            overlayManager.hideCurrentOverlay(ofPriority: .modal)
This looks like a bad merge.

2022-06-01 06:07 UTC, darinwf commented on Client/Frontend/Browser/Card/ArchivedTabsListSectionView.swift
> +struct ArchivedTabsListSectionVIew: View {
nit: `VIew` -> `View`

2022-06-01 06:07 UTC, darinwf commented on Client/Frontend/Browser/Tabs/Tab.swift
> +        let minusOneWeekToCurrentDate =
Some of this code looks like it is duplicated into TabGroup. We should avoid duplicating this code.

2022-06-01 06:07 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +    var activeTabs: [Tab] {
Are you still planning on making this a stored property?

2022-06-01 06:07 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +        let tabGroups = getAll()
This looks expensive. Why didn't you want to just enumerate `activeTabGroups` and `archivedTabGroups` to get the set of all rootUUID -> title mappings?

2022-06-01 06:09 UTC, chassu commented on Client/Frontend/Browser/Tabs/TabGroup.swift
> +        self.lastExecutedTime =
I think you're right. Part of my change is to modify `TabGroup.lastExecutedTime` on `TabManager.selectTab`. I think turning it into a computed property makes sense.

2022-06-01 06:26 UTC, chassu commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +        let tabGroups = getAll()
I was thinking about a case where child tabs of a tab group span across activeTabGroups and archivedTabGroups: the title for sides should be consistent. `displayTitle` simply gets the title of the first child, which means the second loop could overwrite the first title. Also, I noticed that the change we discussed will make custom tab group title no longer persistent because of `temp[group.key] = group.value.displayTitle`. I think we might actually need to keep the nil check (to not overwrite custom tab group names).

2022-06-01 06:31 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
>              }
I see. Hmm...

Is the goal of this function merely about garbage collecting elements of `tabGroupDict` that are no longer needed after a tab group is removed, or is its purpose more than that?

Perhaps an alternative would be to add to `tabGroupDict` upon forming a tab group for the first time.

Then this function would only need to be concerned with pruning tab group names that no longer exists.

OK for this to be a follow-up PR, I think.

The current code deserves a comment explaining why it is necessary to compute the merged set of tab groups.

2022-06-01 07:44 UTC, chassu commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
>              }
I think another goal of the function is to write newly created tab group's title into the dictionary. I'll undo the changes on this function and make some comments. We can figure out a follow-up PR to handle this.

2022-06-01 19:59 UTC, chassu commented on Client/Frontend/Browser/Tabs/Tab.swift
> +        let minusOneWeekToCurrentDate =
I tried to make a public func in Shared/TimeConstants.swift, but got complaints because I"m using FeatureFlag in the function. I define the public func inside Tab.swift. What do you think?

2022-06-02 05:22 UTC, darinwf reviewed
This PR is complicated! I wish there were a way to break it down into simpler pieces.

2022-06-02 05:22 UTC, darinwf commented on Client/Frontend/Browser/Card/ArchivedTabsListSectionView.swift
> +        return tabGroupDict.reduce(into: [String: Bool]()) { dict, groupName in
This looks potentially expensive. Can some of the processing be moved to a ViewModel? We have learned that we should keep the `body` of our Views computationally as simple as possible.

2022-06-02 05:22 UTC, darinwf commented on Client/Frontend/Browser/Card/ArchivedTabsListSectionView.swift
> +                            LazyVStack(spacing: 0) {
Nested LazyVStacks make me worry.

2022-06-02 05:22 UTC, darinwf commented on Client/Frontend/Browser/Card/ArchivedTabsListSectionView.swift
> +                        // A tab group can have child tabs spread across different archived sections.
This is begging for ViewModel treatment instead of doing this work in the `body`.

2022-06-02 05:22 UTC, darinwf commented on Client/Frontend/Browser/Card/ArchivedTabsPanelModel.swift
> +            self?.tabManager.updateTabGroupsAndSendNotifications(notify: false)
This feels backwards. Why is ArchivedTabsPanelModel responsible for calling `updateTabGroupsAndSendNotifications`? Shouldn't `TabManager` be the one to observe `archivedTabsDuration` itself and drive the updates?

The flow of updating should be more one directional. TabManager observes its inputs and generates notifications. Downstream from that the ArchivedTabsPanelModel would notice when TabManager changes and then update its data accordingly.

2022-06-02 05:22 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +    private(set) var updateGroupPublisher = PassthroughSubject<Void, Never>()
Please add a comment explaining this new publisher.

2022-06-02 05:22 UTC, darinwf commented on Client/Frontend/Browser/Card/CardModels.swift
> +            manager.updateTabGroupsAndSendNotifications(notify: false)
I think we should avoid calling updateTabGroupsAndSendNotifications from outside of TabManager. Can it be the one that knows when it should do this work?

2022-06-02 05:22 UTC, darinwf commented on Client/Frontend/Browser/Card/CardModels.swift
> +        } else if needsUpdateRows || forceUpdateRows {
I'm confused by the `else` here. Why are these branches mutually exclusive? What if both `needsUpdateGroup` and `needsUpdateRows` are true?

2022-06-02 05:22 UTC, darinwf commented on Client/Frontend/Browser/Card/CardModels.swift
> +        } else if needsUpdateRows || forceUpdateRows {
Oh, I get it... `onDataUpdated` also calls `updateRows`. This is not very clear. Should you also clear `needsUpdateRows` before calling `onDataUpdated`?

2022-06-02 05:22 UTC, darinwf commented on Client/Frontend/Browser/Card/BrowserPrimitive.swift
> +    func selectTabFromArchive(_ tab: Tab) {
rather than introduce this special function that must be used to pull a tab out of the archive, why don't you just make `selectTab` work? i worry there could be other paths that might lead to selecting an archived tab. e.g., createOrSwitchToTab. it is going to get messy if we need to special case all calls to selectTab to check if the tab is archived. TabManager should just do this internally.

Can't selectTab just notice that it is selecting an archived tab and then trigger all of the tab group updating logic? Is the issue that you need to do that lazily from hideGridWithAnimation?

2022-06-02 05:22 UTC, darinwf requested changes
Requesting changes per above comments

2022-06-02 09:04 UTC, chassu commented on Client/Frontend/Browser/Card/BrowserPrimitive.swift
> +    func selectTabFromArchive(_ tab: Tab) {
Made the change to make selectTab work. Had to add an argument to other places too because of the SelectingManager protocol.

2022-06-02 21:47 UTC, darinwf commented on Client/Frontend/Browser/Tabs/Tab.swift
> +    func isArchived() -> Bool {
nit: Probably would be nicer as a computed property

2022-06-02 21:47 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +            if updateGroup {
Rather than force the caller to know if this call to selectTab will alter tab groups, why not just have TabManager determine that? We can just check `tab.isArchived` right?

2022-06-02 21:54 UTC, chassu commented on Client/Frontend/Browser/Card/BrowserPrimitive.swift
> +    func selectTabFromArchive(_ tab: Tab) {
We need to update tab data when a tab is selected from archives because 1. they are not an active tab 2. they belong to a tab group. So the publisher is needed to make sure `CardModel.onDataUpdated` gets called so the CardGrid is up to date.

2022-06-02 21:59 UTC, darinwf commented on Client/Frontend/Browser/Card/BrowserPrimitive.swift
> +    func selectTabFromArchive(_ tab: Tab) {
Why not just have TabManager call `updateTabGroupsAndSendNotifications` passing `notify: true`? Is there some reason why calling `tabsUpdatedPublisher.send()` from within `selectTab` wouldn't work?

2022-06-02 22:34 UTC, chassu commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
>          selectedTab.lastExecutedTime = Date.nowMilliseconds()
need to save `isArchived` ahead of time because updating `lastExecutedTime` could change the value we want to read.

2022-06-02 22:49 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +                updateTabGroupsAndSendNotifications(notify: true)
Should we hoist this out of the `if notify` block so we run `updateTabGroupsAndSendNotifications` always and just vary the `notify` parameter. So like this:

```
if isArchived {
    updateTabGroupsAndSendNotifications(notify: notify)
}
if notify {
    ...
}
```

2022-06-02 23:08 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager+CloseTabs.swift
> +        updateSelectedTab: Bool = true, fromArchive: Bool = false
consider adding two parameters here instead that are more descriptive about the functions here:

`notify: Bool` and `dontAddToRecentlyClosed: Bool`

2022-06-03 05:03 UTC, darinwf approved these changes

2022-06-03 09:35 UTC, merged