Select Tab Improvements
neevaco/neeva-ios pull request #3598
Opened 2022-05-13 20:51 UTC by evancrow

Fixes a bug where selecting a tab while the `CardGrid` was still opening would select it but wouldn't open it. Also wait to create WebView until after the animation completes.

## Checklists
### How was this tested?
- [x] I tested this manually

## Issues addressed
Fixed: #2885

2022-05-18 01:01 UTC, darinwf commented on Client/Frontend/Browser/Card/BrowserPrimitive.swift
>      func select(_ tab: Tab) {
A specialization of `CardDetails.onSelect` on `TabCardDetails` might be a better choice since it moves the handling closer to the UI?

2022-05-19 01:24 UTC, evancrow commented on Client/Frontend/Browser/Tabs/Tab.swift
> +    func createWebViewOrReloadIfNeeded() {
It will actually only do one or the other. It either will create the `WebView` or will reload it if wasn't created and needs to be reloaded.

2022-05-19 01:42 UTC, evancrow commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +        selectedTabWebViewPublisher.send(selectedTab?.webView)
I think it is appropriate to send `nil` events, `TabContainerModel` also listens for a nil `WebView`. Will add a comment.

2022-05-20 05:17 UTC, darinwf requested changes

2022-05-20 05:17 UTC, darinwf commented on Client/Frontend/Browser/BrowserModel.swift
> +        if showGrid, cardTransitionModel.state == .visibleForTrayShow {
nit: I suggest writing the comment more like this:

```
// It's possible for a new transition animation to begin before the previous one
// had finished, so we need to check `cardTransitionModel.state` here as well.
```

No need to mention the bug being fixed. Rather just important to let the reader
know why we are checking both variables.

2022-05-20 05:17 UTC, darinwf commented on Client/Frontend/Browser/Card/BrowserPrimitive.swift
> +        manager.selectTab(self, createWebView: false, notify: true)
I still feel like this is potentially error prone. We have an extension here to `Tab` that adds a `select` method. We don't know **for sure** that `Tab.select` is only called when the user taps on a tab in the card grid. We don't know that the card transition animation is going to run in this case. This is why I suggested the approach of setting a flag on `Tab` instead from `TabCardDetails.onSelect`.

2022-05-20 05:17 UTC, darinwf commented on Client/Frontend/Browser/Tabs/Tab.swift
> +    func createWebViewOrReloadIfNeeded() {
Oh, I missed that. Thanks!

2022-05-20 05:17 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +            if !createWebView && tab?.webView != nil {
So we should remove this nil-check right? The reason I asked about reporting nil values was because I was wondering about this case.

2022-05-20 05:17 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager.swift
> +            updateWebViewForSelectedTab()
I think it's important to not send notifications here if `notify` is false, and we should defer notifications until the `if notify {` block below.

My recommendation is to create the WebView here like you are doing, but to create a local variable named `notifyWebViewPublisher` that you can set to true here in case you do need to notify it, and then defer that notification to the `if notify {` block below.

2022-05-21 17:29 UTC, darinwf commented on Client/Frontend/Browser/Card/Card.swift
> -                    details.onSelect()
I'm curious, why didn't you want to set the flag on `Tab` from `onSelect`? It seems like that would have been simpler and not require changes to `hideGridWithAnimation`.

It seems like one of the potential problems with trying to set it in `hideGridWithAnimation` is that you don't know if the tab will be selected before or after the call to `hideGridWithAnimation`.

I get that you are changing that by moving `onSelect` to happen after `selectionCompletion`.

Were you thinking that it would help for what happens in `hideGridWithAnimation` and `hideGridWithNoAnimation` to be paired up? I think that actually makes a ton of sense.

If so, then I think we should do a couple things:

1. We should rename the `selectedTab` parameter to `tabToBeSelected` to make it more clear that this is the tab that is about to be made the selected tab.
2. The `shouldCreateWebViewUponSelect` flag should be set earlier just in case some other code in `hideGridWithAnimation` would lead to `selectTab` getting called.

OK, that said... I see a potential problem:

The code in `hideGridWithAnimation` checks to see if it needs to update `incognitoModel`, but if the tab to be selected hasn't been selected yet, then the incognito state should never need to be updated. This `incognitoModel` updating is now in the wrong place? Does it need to be moved elsewhere? Is it even needed?

I'd be curious to go back to when we added this `incognitoModel` updating to see if it is still necessary. Perhaps it should not be since `TabManager.selectTab` should take care of updating incognito state.

2022-05-23 16:37 UTC, evancrow commented on Client/Frontend/Browser/Card/Card.swift
> -                    details.onSelect()
Made your two suggested changes. The `incognitoUpdate` has to stay where it is, without it, the animation is broken if you tap done while the `selectedTab` is in normal mode while viewing incognito tabs (and vice versa). I did clean it up a bit though.

2022-05-23 16:44 UTC, darinwf approved these changes
Thanks!

2022-05-23 17:40 UTC, merged