Settings; customize app icon and theme override
neevaco/neeva-ios pull request #3648
Opened 2022-05-21 04:44 UTC by jedireza

This PR adds the ability to change the app icon and also change the theme of the app separate from the system theme.

## Checklists

### How was this tested?
- [x] I tested this manually

### Manual test cases
I tested in the simulator.

### Screenshots and screen recordings

#### Change the app icon

#### Change app icon

https://user-images.githubusercontent.com/979929/169635672-851ce4ce-2653-4b04-bacd-59dc90b8d49e.mp4

#### Change theme

https://user-images.githubusercontent.com/979929/169635748-13100cbf-bf37-46bc-a0c2-07478c6e2218.mp4

## Issues addressed
N/A

2022-05-21 06:14 UTC, evancrow requested changes
Super neat, just a few things I think should be addressed.

2022-05-21 06:14 UTC, evancrow commented on Client/Application/SceneDelegate.swift
> +    private(set) static var shared: SceneDelegate?
Strongly against a static `SceneDelegate` instance. I recommend using one of the `getCurrentSceneDelegate` methods, and if you can't plumb through any of the parameters, as a last resort use `getCurrentSceneDelegateOrNil`.

2022-05-21 06:14 UTC, evancrow commented on Client/Frontend/Settings/CustomizeSettingsSection.swift
> +                    Defaults[.customizeTheme] = option
Should probably move a lot of this to the `SceneDelegate` or a separate model so we don't have lots of logic inside a `View`.

2022-05-21 06:14 UTC, evancrow commented on Client/Application/SceneDelegate.swift
> +            if Defaults[.customizeTheme] == .dark {
Likely can just write this as a `ternary`, not too important though

2022-05-21 06:14 UTC, evancrow commented on Client/Frontend/Settings/CustomizeSettingsSection.swift
> +    @ViewBuilder var iconNavLink: some View {
nit: start `var` on a new line underneath `@ViewBuilder`

2022-05-21 17:41 UTC, darinwf submitted a review, later dismissed

2022-05-21 17:41 UTC, darinwf commented on Client/Application/SceneDelegate.swift
> +    private(set) static var shared: SceneDelegate?
Yeah, on iPad the user can create multiple browser windows and each one is represented by a scene. We end up with N `SceneDelegate` instances in other words. Each has its own `BVC` and `TabManager`.

2022-05-21 17:43 UTC, darinwf commented
Let's review the UI changes in iOS design sync on Monday.

2022-05-21 18:16 UTC, jedireza commented on Client/Application/SceneDelegate.swift
> +    private(set) static var shared: SceneDelegate?
Thanks for bringing this up! I adjusted the cost to handle all scenes and uploaded a new video demonstrating this working.

2022-05-21 18:17 UTC, jedireza commented on Client/Frontend/Settings/CustomizeSettingsSection.swift
> +                    Defaults[.customizeTheme] = option
Yep, done.

2022-05-21 18:17 UTC, jedireza commented on Client/Application/SceneDelegate.swift
> +            if Defaults[.customizeTheme] == .dark {
This is gone now.

2022-05-21 18:25 UTC, jedireza commented on Client/Frontend/Settings/CustomizeSettingsSection.swift
> +    @ViewBuilder var iconNavLink: some View {
Maybe we should consider the `wrapAttributes` rule for our swift format options? https://github.com/nicklockwood/SwiftFormat/blob/master/Rules.md#wrapattributes

2022-05-23 20:56 UTC, evancrow approved these changes
Code LGTM, thanks! should still wait for design approval :)

2022-05-25 22:50 UTC, Ria-yu commented
Designer input:

We sync-ed on this in iOS Design Open Hours [(notes)](https://paper.dropbox.com/doc/Mobile-Design-Open-Hours-iOS-Android--BiNeTHC~wGLgqDKWc4zSfSYLAg-94JrusTJaq0a3NRhIgcqk#:uid=816781856239286097298723&h2=May-25%2C-2022---iOS) and agreed on these decisions: 
        - Section name: ‘Appearance’
        - Theme choice: Ship as-is. Decouple web / app syncing, and investigate all possible cases with and without Neeva browser context, mobile and desktop.
        - Icon choices:  
            - ship with only 2 options (light Neeva logo, and dark Neeva logo)
            - Dark Neeva logo: 
                - There’s no official logo today. 
                [x] AI:  Ria to make an official dark logo v1 — Thanks Ria! [@Ria Y]
                - Logo assets Figma: https://www.figma.com/file/pQX1oZi3WFeIVTazdOKhST/Logos?node-id=2707%3A865

According to Reza's updates in #design-mobile Slack channel, the decisions above are reflected in the latest PR. In that case, designers are happy to approve this :).

2022-05-25 22:55 UTC, merged