Time based switcher removeTab logic fix
neevaco/neeva-ios pull request #3762
Opened 2022-06-02 20:04 UTC by chassu

Make sure removeTab always runs and guard the index after it happens.

### How was this tested?
- [x] I tested this manually

### Screenshots and screen recordings
Before:

https://user-images.githubusercontent.com/87332917/171728472-31dbc124-8616-443c-8aa2-e4885dfb7a92.mp4

After:

https://user-images.githubusercontent.com/87332917/171728489-89215f3e-0faa-41c8-9370-e27eb24a86ec.mp4

2022-06-02 20:31 UTC, evancrow approved these changes
LGTM

2022-06-02 20:44 UTC, darinwf requested changes

2022-06-02 20:52 UTC, chassu commented on Client/Frontend/Browser/Tabs/TabManager/TabManager+CloseTabs.swift
> +
`removeTab` was failing to remove the tab if the tab is not in the today section, this change is fixing that. It's a regression from #3659.

The filter only looks at today's section to make sure the select leftOrRightTab doesn't select a tab from a different section.

2022-06-02 21:34 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager+CloseTabs.swift
> +
Oh, lol. I was commenting on the existing code 🤦 

I agree, your change here makes sense. But instead of making a copy normalTabs and incognitoTabs, why not just defer the return?

2022-06-06 18:46 UTC, chassu commented on Client/Frontend/Browser/Tabs/TabManager/TabManager+CloseTabs.swift
> +
what do you mean by deferring the return here? I think it was necessary to save a copy of the array because `removeTab()` is going to modify the arrays.

2022-06-06 21:03 UTC, darinwf commented on Client/Frontend/Browser/Tabs/TabManager/TabManager+CloseTabs.swift
> +
Looking at the old code, you could simply defer the guard of `index` until after `removeTab`. But you can still compute `index` before `removeTab` as the current code does. Then you don't need to bother with saving `normalTabs` and `incognitoTabs` as this PR does. Just defer the nil check and `return` statement.

2022-06-09 21:48 UTC, merged