Re-revert sort feature
neevaco/neeva-ios pull request #4047
Opened 2022-07-14 19:55 UTC by buracules

_General description of what your PR does, written in a way that someone six
months from now could understand what you were doing when tracking down a bug
or attempting to add new functionality_

* More details about the changes
* Even more details about the changes
* Yet more details about the changes

## Checklists

### How was this tested?
- [ ] I tested this manually
- [ ] I added automated tests
- [ ] Existing automated tests are enough to cover my changes

### Manual test cases
If manually tested, describe the different scenarios you followed to ensure
that your changes work.  Make sure that you've tested as many pathways as
possible -- not just the [happy path](https://en.wikipedia.org/wiki/Happy_path).

### Screenshots and screen recordings
Images or videos showing the effect of your PR.  Examples include:
* For new Views, add images of `_Previews` you have added for both light
  and dark mode
* Before and after screenshots showing the effect of your styling changes
* Videos showing you performing the flow that you have changed

## Issues addressed
* Link(s) to Github issue(s) (if applicable)

2022-07-15 17:57 UTC, buracules commented on Client/Frontend/Browser/Card/CardModels.swift
> +            ? filteredCollection.count - 1 : collection.count
No idea why `collection.count - 1 `works correctly and why this is not out of bounds.

2022-07-18 20:47 UTC, yozuysal reviewed
hmm so we are not reintroducing the smaller view model?

2022-07-18 20:47 UTC, yozuysal commented on Client/Frontend/Overlay/Content/Spaces/SpacesFilterView.swift
> -        .overlayIsFixedHeight(isFixedHeight: true)
is this intentionally removed?

2022-07-18 20:51 UTC, buracules commented
> hmm so we are not reintroducing the smaller view model?

I can put everything in viewModel but i have store it in SpaceCardModel.

2022-07-18 21:15 UTC, buracules commented
> > > hmm so we are not reintroducing the smaller view model?
> > 
> > 
> > I can put everything in viewModel but i have store it in SpaceCardModel.
> 
> yes, that sounds good. We can have SpaceCardModel instantiate and own the new model and reference it as a ObservedObject.

For observing allDetails i have to pass SpaceCardModel to the ViewModel but it will create a retain cycle. SpaceCardModel will have viewModel and viewModel will have SpaceCardModel.

2022-07-18 22:11 UTC, yozuysal commented on Client/Frontend/Browser/Card/CardModels.swift
> +    @ObservedObject var viewModel: SpaceCardViewModel = SpaceCardViewModel()
no need for observedobject here

2022-07-18 22:11 UTC, yozuysal commented on Client/Frontend/Browser/Card/CardListViews.swift
> +            ForEach(spacesModel.viewModel.dataSource, id: \.id) { details in
we should have 

`@ObservedObject var viewModel = spaceModel.viewModel`

at the top here so that it reacts to changes in the published variable properly

2022-07-18 22:16 UTC, buracules commented on Client/Frontend/Browser/Card/CardListViews.swift
> +            ForEach(spacesModel.viewModel.dataSource, id: \.id) { details in
I have to pass spacesModel in initializer like it used to be

2022-07-18 22:28 UTC, yozuysal approved these changes

2022-07-18 22:37 UTC, EdwardJTL requested changes
sorry for the late review

2022-07-18 22:37 UTC, EdwardJTL commented on Client/Extensions/MutableCollectionExtensions.swift
> +extension MutableCollection where Self == [SpaceCardDetails] {
i think this is really saying `Array where Element: SpaceCardDetails` when you ask `Self` to conform to an array.

overall i'd suggest cleaning up this file so that each extension is defined on the appropriate corresponding collection protocol.

2022-07-18 22:37 UTC, EdwardJTL commented on Client/Frontend/Browser/Card/CardDetails.swift
> +        guard let item = item else { return nil }
could you put this on separate lines so that a breakpoint can be easily added.

2022-07-18 22:37 UTC, EdwardJTL commented on Client/Frontend/Browser/Card/CardDetails.swift
> +        for i in stride(from: 0, to: filteredCollection.count, by: 1) {
would `filteredCollection.indices` work here?

2022-07-18 22:37 UTC, EdwardJTL commented on Client/Frontend/Browser/Card/CardDetails.swift
> +            else { return nil }
same here

2022-07-18 22:37 UTC, EdwardJTL commented on Client/Frontend/Browser/Card/CardModels.swift
> +        let comparisonValue = self[keyPath: sortType.keyPath]
could this just use a switch instead of using keypath and waiting a call from the date formatter?

2022-07-18 22:37 UTC, EdwardJTL commented on Client/Frontend/Browser/Card/CardModels.swift
> +        if let date = ISO8601DateFormatter().date(from: comparisonValue) {
creating a date formatter and using it for the first time is expensive. could we have a shared instance?

2022-07-18 22:37 UTC, EdwardJTL commented on Client/Frontend/Browser/Card/CardModels.swift
> +
nitL empty line

2022-07-18 22:37 UTC, EdwardJTL commented on Client/Frontend/Browser/Card/CardModels.swift
> +        dataSource[index].updateSpace()
this is an async call right? `findIndex` might be called too soon..?

2022-07-18 23:01 UTC, EdwardJTL reviewed
did some instrumentation and added additional comments

2022-07-18 23:01 UTC, EdwardJTL commented on Client/Frontend/Browser/Card/CardModels.swift
> +                    .sortSpaces(by: sort, order: order)
another optimization is to apply sort and filter in separate pipelines. 
all spaces -> sort -> store data
stored sorted data -> filter -> filtered and sorted data.
this one the more expensive sort is applied less frequently

2022-07-18 23:04 UTC, buracules commented on Client/Extensions/MutableCollectionExtensions.swift
> +                guard let firstItem = $0.item?.getComparisonValue(for: sortType),
I thnik its because of dateFormatter. I think i can just convert and store in space creation also use switch case instead of keyPath

2022-07-19 17:10 UTC, buracules commented on Client/Frontend/Overlay/Content/Spaces/SpacesFilterView.swift
> +                }.accentColor(.label)
What should i use instead?

2022-07-19 17:58 UTC, EdwardJTL commented on Client/Frontend/Overlay/Content/Spaces/SpacesFilterView.swift
> +                }.accentColor(.label)
the new one is
func tint(_ tint: [Color](doc://com.apple.documentation/documentation/swiftui/color)?) -> some [View](doc://com.apple.documentation/documentation/swiftui/view)
but annoyingly that one is iOS15+
also, GroupedRowButtonView applies `TableCellButtonStyle` style to it, where it sets `.foregroundColor(.accentColor)`, maybe you can work with that and pass in a Bool so it becomes `.foregroundColor(useAccent ? .accentColor : nil)`?

2022-07-19 17:58 UTC, EdwardJTL commented on Client/Frontend/Overlay/Content/Spaces/SpacesFilterView.swift
>                          spaceCardModel.objectWillChange.send()
ah i was saying maybe `spaceCardModel.objectWillChange.send()` signal should be sent after the other view model's properties get updated?

2022-07-20 17:56 UTC, merged