[i18n] Enable compiler extract localized string flag and misc fixes
neevaco/neeva-ios pull request #4080
Opened 2022-07-22 23:38 UTC by chung-lai

## Checklists

### How was this tested?
- [ ] I tested this manually
- [ ] I added automated tests
- [ ] Existing automated tests are enough to cover my changes

2022-07-25 16:56 UTC, darinwf approved these changes
LGTM, just a couple things:

2022-07-25 16:56 UTC, darinwf commented on Client/Frontend/Browser/CookieCutter/CookieCutterOnboardingView.swift
> +                            "Your Cookie Cutter just declined a **cookie popup** and blocked \(trackingStatsViewModel.numTrackers) **trackers**"
This only works in iOS 15 and later right? I guess that is okay. Have you checked out what happens on an iOS 14 device / simulator?

2022-07-25 17:19 UTC, chung-lai commented on Client/Frontend/Browser/CookieCutter/AdBlockerPromoView.swift
> +                Text(verbatim: "Block Intrusive Ads")
This promo modal only shows for existing users so it shouldn't apply for new users who download the latest app.

2022-07-25 17:58 UTC, chung-lai commented on Client/Frontend/Browser/CookieCutter/CookieCutterOnboardingView.swift
> +                            "Your Cookie Cutter just declined a **cookie popup** and blocked \(trackingStatsViewModel.numTrackers) **trackers**"
Interesting, it works though i'll need to file separate issue for cookie cutter not functioning in iOS 14 :P :

<img width="564" alt="Screen Shot 2022-07-25 at 10 57 44 AM" src="https://user-images.githubusercontent.com/87332578/180843289-2d2dcef3-3746-48ae-ab23-6a9d675a7f3f.png">

2022-07-25 23:57 UTC, darinwf approved these changes

2022-07-25 23:57 UTC, darinwf requested changes

2022-07-25 23:57 UTC, darinwf commented on Client/en.lproj/Localizable.strings
> +"Past 30 Days" = "Yesterday";
Actually, this looks like a typo

2022-07-26 00:24 UTC, chung-lai commented on Client/en.lproj/Localizable.strings
> +"Past 30 Days" = "Yesterday";
Thanks for catching that!

2022-07-26 00:25 UTC, darinwf approved these changes
Approving so you aren't blocked.

2022-07-26 05:31 UTC, merged