Fix Spaces Flakiness
neevaco/neeva-ios pull request #4136
Opened 2022-08-02 23:31 UTC by buracules

Fixed flakiness on space details screen.

The main problem was when we create a space item we are giving random id to the item. To fix that now i am calling refresh function when we add a new item.

## Checklists

### How was this tested?
- [x] I tested this manually
- [ ] I added automated tests
- [ ] Existing automated tests are enough to cover my changes

### Screenshots and screen recordings
Images or videos showing the effect of your PR.  Examples include:

#### Before
https://user-images.githubusercontent.com/15333612/182493051-78f35c9c-28ab-4011-8c5b-ca516bf7c1c4.mp4 

#### After
https://user-images.githubusercontent.com/15333612/182493172-30fc74ed-70f9-4f88-9b29-e8305c26ed2e.mp4

## Issues addressed
* Fixes #4121

2022-08-02 23:35 UTC, yozuysal commented
when you say "when we create a space item", does that include regular clicks to the bookmark button or only to create a new item by giving url, title, description in the UI?

2022-08-02 23:35 UTC, yozuysal commented
(I think the cases we heard does cover just regular uses of the  bookmark button as well. So trying to make sure)

2022-08-02 23:37 UTC, buracules commented
> when you say "when we create a space item", does that include regular clicks to the bookmark button or only to create a new item by giving url, title, description in the UI?

Hmm i dont think so. Right now its only to create new item from spaces ui. Let me check the other one as well.

2022-08-02 23:39 UTC, yozuysal commented
My interpretation was @evancrow was also running into this while just using the bookmark button as well. is that correct @evancrow ? Or were you using the + button from the detail UI?

2022-08-02 23:40 UTC, yozuysal commented
Actually @evancrow another question, were you getting a "an error occurred" toast when you add items or was it failing in some different way?

2022-08-02 23:56 UTC, evancrow commented
No error Toast. Sorry for the confusion on this, I sent some clarification to @buracules earlier in the form of a screen recording which I'll attach here too. All of the issues I had were from the DetailView ui. 

One example:
https://user-images.githubusercontent.com/37356984/182496191-41022342-d083-49d8-bcbc-16abe0027b90.MOV

2022-08-02 23:59 UTC, buracules commented
> No error Toast. Sorry for the confusion on this, I sent some clarification to @buracules earlier in the form of a screen recording which I'll attach here too. All of the issues I had were from the DetailView ui. All were just around things either showing up after being deleted, duplicates after restoring an item, or items showing in the wrong order.
> 
> One example: https://user-images.githubusercontent.com/37356984/182496191-41022342-d083-49d8-bcbc-16abe0027b90.MOV

Is this reordering issue also happening after you add an item?

2022-08-03 00:00 UTC, evancrow commented
Yup!

2022-08-03 00:04 UTC, darinwf commented
Can you add an automated test to ensure that this does not regress again?

2022-08-03 03:18 UTC, buracules commented
Sure i will look into it tomorrow with broken tests. 

I was trying to find what cause this and i tested with v1.33.4 and that version also has this bugs. It was happening for months and we had no idea

2022-08-03 04:58 UTC, evancrow commented
@buracules Can we also say that this PR fixes #3918?

2022-08-03 15:27 UTC, buracules commented
@evancrow It must be. But i will double check after i am done with broken tests.

2022-08-03 16:58 UTC, buracules commented
CC @jonathangarelick

2022-08-03 17:00 UTC, buracules commented on Client/Frontend/Browser/CardGrid/Card/CardModels.swift
> +    var asdCancellable: AnyCancellable?
oh that was for test i tought i deleted this one

2022-08-03 17:30 UTC, buracules commented on Client/Frontend/Browser/CardGrid/AddOrUpdateSpaceView.swift
> +                                })
Yes that makes sense i tried different things with this setup but now i dont need completion i can just call refresh

2022-08-03 17:55 UTC, EdwardJTL requested changes

2022-08-03 17:55 UTC, EdwardJTL commented on Client/Frontend/Browser/CardGrid/AddOrUpdateSpaceView.swift
> +                                onCompletion: {
nit: use trailing closure

2022-08-03 17:55 UTC, EdwardJTL commented on Client/Frontend/Browser/CardGrid/Card/CardModels.swift
>              request?.$state.sink { state in
all of these should capture `[weak self]` since you are storing it on `self` now

2022-08-03 17:55 UTC, EdwardJTL commented on Client/Frontend/Browser/Spaces/SpaceDetailList.swift
> +        if let spaceID = primitive.item?.id.id, let space = SpaceStore.shared.get(for: spaceID) {
nit: separate lines

2022-08-03 17:55 UTC, EdwardJTL commented on Client/Frontend/Browser/Spaces/SpaceDetailList.swift
> +            for index in 0..<entities.count {
is this the same as 
`primitive.allDetails = entities.reversed() + primitive.allDetails`?

2022-08-03 17:55 UTC, EdwardJTL commented on Client/Frontend/Browser/CardGrid/Card/CardModels.swift
>              let request = SpaceServiceProvider.shared.addToSpaceWithURL(
should these requests be completion handlers instead? i don't see the point of using combine for them.

2022-08-03 17:56 UTC, buracules commented on Client/Frontend/Browser/CardGrid/AddOrUpdateSpaceView.swift
> +                                onCompletion: {
Will remove this

2022-08-03 18:28 UTC, buracules commented on Client/Frontend/Browser/CardGrid/Card/CardModels.swift
> +                    SpaceStore.shared.refreshSpace(spaceID: spaceID)
Yes. Since we add a new item we dont know its ID and thats the biggest issue. When we reorder, delete we need that id for others we can make local changes

2022-08-03 18:56 UTC, buracules commented
> Reordering and deleting works well so far, but when I add an item to a Space, the Space doesn't go to the top of the grid.
> 
>  Simulator.Screen.Recording.-.iPhone.13.-.2022-08-03.at.11.40.59.mp4

I think we have to update lastModifiedTs/timestamp

2022-08-03 19:23 UTC, buracules commented
> Also editing a Space name is not updating for me. It does update on the web interface in real time though.
> 
>  Simulator.Screen.Recording.-.iPhone.13.-.2022-08-03.at.11.43.38.mp4 
> note: it does update when I go back to the main grid, then revisit the detail page.

I remember we were talking with @yozuysal about update issues. But i couldn't figure out the reason. But we can do the same thing and refresh for now? What do you think?

2022-08-03 21:01 UTC, buracules commented
> > > Also editing a Space name is not updating for me. It does update on the web interface in real time though.
> > > Simulator.Screen.Recording.-.iPhone.13.-.2022-08-03.at.11.43.38.mp4
> > > note: it does update when I go back to the main grid, then revisit the detail page.
> > 
> > 
> > I remember we were talking with @yozuysal about update issues. But i couldn't figure out the reason. But we can do the same thing and refresh for now? What do you think?
> 
> Yes I think generally what we should do here is revert to the previous behavior when necessary in order to get things working again. Then we can file an issue to deal with optimizing it later.

It's not working I remember this one i had to give random ids to views in order to work. But that's another problem.

2022-08-03 21:07 UTC, EdwardJTL commented on Client/Frontend/Browser/CardGrid/Card/CardModels.swift
>              let request = SpaceServiceProvider.shared.addToSpaceWithURL(
yes, combine is good at setting up processing pipelines and/or processing data that comes in a sequence.

in this case, the syntax makes the intention of the code less clear. it is suggesting that `$state` could publish multiple values, and that we want to keep observing the publisher. That's why I am suggesting a completion handler approach here.

2022-08-04 17:33 UTC, EdwardJTL reviewed
some more weak self missing

2022-08-04 17:33 UTC, EdwardJTL commented on Client/Frontend/Browser/CardGrid/Card/CardModels.swift
>              request?.$state.sink { state in
[weak self]

2022-08-04 17:33 UTC, EdwardJTL commented on Client/Frontend/Browser/CardGrid/Card/CardModels.swift
> +                }.store(in: &self.mutationSubscriptions)
ditto

2022-08-04 17:33 UTC, EdwardJTL commented on Client/Frontend/Browser/CardGrid/Card/CardModels.swift
>              request?.$state.sink { state in
ditto

2022-08-04 19:30 UTC, evancrow commented
My issues seem to be fixed, so LGTM. I do notice that it takes a second or two for the app to correct itself, is this because it has to call SpaceService to update?

2022-08-04 19:36 UTC, buracules commented
> My issues seem to be fixed, so LGTM. I do notice that it takes a second or two for the app to correct itself, is this because it has to call SpaceService to update?

Probably yes. This was just a quick fix for next step we can use the id from response instead of refreshing the space.

2022-08-04 21:24 UTC, EdwardJTL commented on Client/Frontend/Browser/CardGrid/Card/CardModels.swift
>              request?.$state.sink { state in
there is one more here in the final change?

2022-08-04 21:25 UTC, EdwardJTL commented
> @EdwardJTL I think you need to approve, it says the PR is still blocked.

there is still one missed weak self :(

2022-08-04 22:00 UTC, EdwardJTL approved these changes
nvm all good

2022-08-04 22:01 UTC, merged