Fix Removing Incognito Tabs When Switching Grid
neevaco/neeva-ios pull request #4452
Opened 2022-10-04 00:24 UTC by evancrow

Fixes a bug where switching from incognito tabs to normal tabs would not remove the incognito tabs even if the `closeIncognitoTabs` setting was enabled.

## Checklists

### How was this tested?
- [x] I added automated tests

## Issues addressed
Fixed: #4405

2022-10-04 04:45 UTC, evancrow commented on Client/Frontend/Browser/Tabs/TabManager.swift
>          incognitoModel.update(isIncognito: tab?.isIncognito ?? isIncognito)
Hmm, would rather not add another observer if we can avoid it.`incognitoModel.update` would set off the observer so this function would be called in the same place either way.

2022-10-04 04:47 UTC, evancrow commented on Client/Frontend/Browser/Tabs/TabManager.swift
> +        removeAllIncognitoTabsForLeavingIncognitoMode()
This line is a condensed version of the code I removed a few lines before. It's necessary if the user switches from incognito mode to normal mode by selecting a tab instead of going through the CardGrid (either by createOrSwitchToTab, history, ArchivedTabs, etc.)

2022-10-04 15:52 UTC, evancrow commented on Client/Frontend/Browser/Tabs/TabManager.swift
> +        removeAllIncognitoTabsForLeavingIncognitoMode()
Try this:

- Incognito Mode
- Open History
- Long press on item -> open in new tab
- Close history (still in incognito)
- Switch to new tab via the Toast

2022-10-04 18:21 UTC, evancrow commented on Client/Frontend/Browser/Tabs/TabManager.swift
> +        removeAllIncognitoTabsForLeavingIncognitoMode()
Will try it out!

2022-10-05 01:04 UTC, EdwardJTL requested changes
should prob fix the tests

code makes sense.

2022-10-05 01:05 UTC, evancrow commented
@jonathangarelick ^^

2022-10-05 01:09 UTC, EdwardJTL commented on Client/Frontend/Browser/Tabs/TabManager.swift
> +            [unowned self] isIncognito in
one consideration. this fires when resources are first initialized.

if you force quit the app:
with flag off, app opens in incognito mode, the tabs stay and is selected.
with flag on, app clears incognito tabs, and opens in non-incognito mode.

We should be aware of this side effect. perhaps @Ria-yu or @darinwf have more opinions.

2022-10-05 01:11 UTC, evancrow commented on Client/Frontend/Browser/Tabs/TabManager.swift
> +            [unowned self] isIncognito in
Wouldn't the incognito tabs not be cleared since the app is loaded in incognito mode so the check `!isIncognito` would fail?

2022-10-05 01:36 UTC, evancrow commented on XCUITests/DeleteIncognitoTabTests.swift
> +        app.switches["Close Incognito Tabs, When Leaving Incognito Mode"].tap()
Nope, just using `tap()` wouldn't turn the toggle on for me. Had to scroll into the visible part of the screen first.

2022-10-05 02:20 UTC, evancrow commented on Client/Frontend/Browser/Tabs/TabManager.swift
> +            [unowned self] isIncognito in
Going back to the original method of calling `removeAllIncongitoTabs` from `selectTab` would fix this issue, I'm pretty sure :)

I don't see much benefit from adding another subscription, especially if it causes another issue to solve when our original method(s) worked fine.

2022-10-05 02:31 UTC, evancrow commented on Client/Frontend/Browser/Tabs/TabManager.swift
> +            [unowned self] isIncognito in
The same issue still occurs, but it would be pretty easy to solve by checking `previous.isIncognito` in `selectTab`. Does that seem reasonable?

2022-10-05 04:28 UTC, evancrow commented
Quick Update after a discussion with @jonathangarelick :

- Reverted the subscription change, went back to my OG fix
- Will follow up on the subscription in a second PR, not focusing on the bug fix

2022-10-06 21:54 UTC, EdwardJTL approved these changes

2022-10-06 22:34 UTC, merged