Zero query promo revamp
neevaco/neeva-ios pull request #4603
Opened 2022-12-15 07:28 UTC by jedireza

This PR revamps the Zero Query promo feature with some updated visuals and new display rules.

## Checklists

### How was this tested?
- [x] I tested this manually
- [x] I added automated tests -- we could always add more 😉

### Manual test cases
I tested in the iPhone and iPad simulators.

### Screenshots and screen recordings
[coming soon]

## Issues addressed
🔒 https://app.clickup.com/t/36034046/GR-2582

2022-12-15 18:05 UTC, EdwardJTL requested changes

2022-12-15 18:05 UTC, EdwardJTL commented on Client/Frontend/ZeroQuery/ZeroQueryModel.swift
> +        if [0, 1, 2, 3, 4].contains(impressionCount % 10) {
`if 0...4 ~= (impressionCount % 10) {`

2022-12-15 18:05 UTC, EdwardJTL commented on Client/Frontend/ZeroQuery/ZeroQueryModel.swift
> +        if [0, 1, 2, 3, 4].contains(impressionCount % 10) {
or `if (impressionCount % 10) < 5 {`

2022-12-15 18:05 UTC, EdwardJTL commented on Client/Frontend/ZeroQuery/ZeroQueryModel.swift
> +        }
can we turn these blocks into `guard else { return }` blocks? it's easier to follow which block exits and which blocks are just mutating

2022-12-15 18:05 UTC, EdwardJTL commented on Client/Logging/LogConfig.swift
> +        case PromoPremiumDismiss
iirc all these new counter paths will be dropped by the backend

2022-12-15 18:05 UTC, EdwardJTL commented
can you also include the link to the figma either on the PR or in click up? thanks!

2022-12-15 18:37 UTC, jedireza commented on Client/Frontend/ZeroQuery/PromoCardView.swift
> +        return
i tried making `innerShadowAmount` static and starting running into more and more IDE errors and warnings. skipping for now.

2022-12-15 18:37 UTC, jedireza commented on Client/Frontend/ZeroQuery/PromoCardView.swift
> +            shape
i think this is fine for now

2022-12-15 18:38 UTC, jedireza commented on Client/Frontend/ZeroQuery/PromoCardView.swift
> +        VStack(content: content)
i think this is fine for now

2022-12-15 18:38 UTC, jedireza commented on Client/Frontend/ZeroQuery/PromoCardView.swift
> +            PromoCardPremiumView(zqModel: zqModel, viewWidth: viewWidth)
i think this is good for now. i don't use this as a "landscape" check.

2022-12-15 18:39 UTC, jedireza commented on Client/Frontend/ZeroQuery/PromoCardView.swift
> +}
i started to make these computed properties like you're suggesting, but ran into issues with the `zqModel` being accessed before the `init` function ran (IDE warning). this is fine for now.

2022-12-15 18:39 UTC, jedireza commented on Client/Frontend/ZeroQuery/PromoCardView.swift
> +    }
this could be a computed prop, but i kept it the same as the `button()` for consistency.

2022-12-15 18:40 UTC, jedireza commented on Client/Frontend/ZeroQuery/PromoCardView.swift
> +        }
i think this is fine for now.

2022-12-15 18:40 UTC, jedireza commented on Client/Frontend/ZeroQuery/ZeroQueryModel.swift
> +        }
i think this is fine for now

2022-12-15 18:41 UTC, jedireza commented on Client/Logging/LogConfig.swift
> +        case PromoPremiumDismiss
open to suggestions on the right way to do this.

2022-12-15 19:27 UTC, EdwardJTL commented on Client/Logging/LogConfig.swift
> +        case PromoPremiumDismiss
there is an allow list of client counters rn, so try to stick to the existing counter paths so you won't need to do any additional work with the logging infra or with the dashboards.
if you really need to add new counters, you can check with Macy on how and if we should be doing that. We are preparing to move all logging to structured logging as well.

2022-12-15 19:35 UTC, jedireza commented on Client/Logging/LogConfig.swift
> +        case PromoPremiumDismiss
@reneehuang1 @macy-n could you take a look and let me know what's best for these metrics?

2022-12-15 19:39 UTC, reneehuang1 commented on Client/Logging/LogConfig.swift
> +        case PromoPremiumDismiss
let's add to allow list for now. I am sure people will want stats on how the promo performed

2022-12-15 23:45 UTC, macy-n commented on Client/Logging/LogConfig.swift
> +        case PromoPremiumDismiss
yup, can just add it to the allow list here: https://source.cloud.google.com/neeva-devinfra/github_neevaco_neeva/+/master:cmd/httpd/logging/counter_filter_allow_list.go;l=183

2022-12-16 01:01 UTC, chung-lai commented on Client/Frontend/ZeroQuery/PromoCardView.swift
> +            "Unlimited ad-free searches",
For these variable based strings, we need to change them to be `LocalizedStringKey` and add them to `Client/Localizable.strings` too. These always get a little tricky :)

2022-12-16 02:38 UTC, jedireza commented
Thanks @chung-lai. We chatted on Slack about how at the render point we're using `LocalizedStringKey` so we should be good if I understood that correctly. I also added the strings to the `./Client/en.lproj/Localizable.strings` file. Could you give it one more look to make sure we got it right?

2022-12-16 03:02 UTC, chung-lai commented on Client/Frontend/ZeroQuery/PromoCardView.swift
> +                    Text(LocalizedStringKey(copy)).font(.system(size: 16))
This is the right way to do this, thanks!

2022-12-16 03:03 UTC, chung-lai commented on Client/Frontend/ZeroQuery/PromoCardView.swift
> +    let copy: String
For future reference, if you change this from `String` -> `LocalizedStringKey`. Then whatever string pass into this should get extracted by the compiler and we don't have to add that string to `Localizable.strings`. The string array (bullets) one is tricker.

2022-12-16 03:03 UTC, chung-lai approved these changes
should be good to go. Left a couple comments for future reference.

2022-12-16 21:42 UTC, merged